version: "3"
services:
  rstudio:
    build:
      context: "."
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/tst"
    environment:
      PASSWORD: ${PASSWORD}
